### ISSUE TITLE
Worst Rust library I have EVER come across 

### ISSUE THREAD

**Issue by HyperAlch** [Vrajs16/fake_user_agent#1]
This is legitimately the worst Rust library I have ever had the dissatisfaction of coming across. I just spent 2 days debugging an issue of websites telling me my applications embedded browser isn't supported, when in fact the issue is your your lazy, piece of garbage library. It is constantly returning chrome versions from 2010 - 2015. Yeah, that would do it. Why on gods green earth would you EVER have people use a fake user agent showing the client as a 2010 - 2015 chrome version? Half of all websites will not even try to run JavaScript with those user agents.

Take this trash down please, so no one else has to suffer from it. Ridiculous

**Comment by HyperAlch** [comment]
It's also very clear, after reading your code, that you copy and pasted a bunch of user agents from an online generator and didn't even look to see if they were up-to-date or valid. You're not generating random agents, your picking from hard coded arrays. Why would you ever publish this on crates.io? I will be reporting this library as fake to crates.io and they can decide to remove it or not. This is behavior I would expect from a high schooler trying to rush a school project, not someone who works professionally.

**Comment by Vrajs16** [comment]
@HyperAlch I am really sorry to hear that my crate caused you problems. I created this crate 7 months ago and has been working fine for my use case ever since. Also these user agents are just copied from [here](https://github.com/fake-useragent/fake-useragent/blob/master/src/fake_useragent/data/browsers.json). Even though the latest file which was updated 2 months ago, it still has all the of old user agents as well.

**Comment by HyperAlch** [comment]
Copy & pasting someone else's work for a personal use case is one thing. But copy & pasting someone else's work without checking it to see if it's up-to-date, throwing it into an array, then abusing Rusts official repo by uploading a crate you barely had an hand in creating, with no intent to maintain and improve is sickening. 

You need to contact crates.io and request that your crate is taken down. This is unacceptable. There was no reason to put this on Rusts official repo. You are going to cause so much damage with your actions and it seems you don't even care. You make me sick.

**Comment by HyperAlch** [comment]
If you don't take it down, I will contact your place of work via social media and ask them if they condone the actions you have displayed. I doubt they will condone it, because this is wrong and you know it.

**Comment by Vrajs16** [comment]
Why would I take this down? Why don't you use something else?
Also I don't why you are being so rude and angry? Anyone can publish anything to crates.io. This crate works for me and if doesn't for you that's fine.

**Comment by HyperAlch** [comment]
There is zero reason this crate should be in the official repo. 

1) It's not your work
2) You don't plan to fix or maintain it
3) Your crate will cause issues for 99% of developers because 10 year old versions of any browser will be blocked by many websites.

Who are you helping by publishing this? It seems like all this crate will do is cause damage except in very small, specific cases. What do you gain from having this published for everyone to use and waste their time on? Please tell me.

PS: I already know you work for UPS, nice try taking it off your profile

**Comment by Vrajs16** [comment]
So what? The place where I copied the user agents has 3.3k stars on GitHub and it still uses things from 10 years ago. I don't really understand what your problem is. Do what ever you please. 😊

**Comment by HyperAlch** [comment]
Dude, that library has a mechanism called `min_percentage` to account for outdated user agents. The library insures that people who want up-to-date agents will get them. 

See that's the thing, when you steal someone else's work without doing any research, you miss important stuff. 

Your library doesn't do this and it's going to cause massive damage. Why wont you just do the right thing? Do you think your cool by having a repo on crates.io? Why do you want the crate to stay up so bad when you know the damage it can cause?

**Comment by HyperAlch** [comment]
Imagine being so dumb that you think library has 3.3k stars just based off a json file, without doing any other research on the library. How did you manage to land a job?

**Comment by HyperAlch** [comment]
I've seen lots of thief's in my time as a programmer. But I've never seen a thief so bad at stealing, that they forget to steal the part of the code that makes the library usable for 99% of the public. If you skim the README for 30 seconds you would have realized that the `min_percentage` mechanism is essential for the library to function properly for most people. 

If your going to keep this piece of trash on crates.io to feed your ego (I see no other reason you would hurt others knowingly), at least credit the original author.
